#pragma once

#define RGB_MATRIX_DISABLE_SHARED_KEYCODES
#define RGBLIGHT_DEFAULT_ON false
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL + 2

#ifdef RGBLIGHT_ENABLE
#   define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#   define RGBLIGHT_EFFECT_SNAKE
#   define RGBLIGHT_EFFECT_KNIGHT
#   define RGBLIGHT_EFFECT_CHRISTMAS
#   define RGBLIGHT_EFFECT_TWINKLE
#   define RGBLIGHT_EFFECT_RAINBOW_MOOD
#endif

#define RGBLIGHT_LAYERS

